
FREEDOM_TRACE_DECODER_GITURL := git@github.com:sifive/freedom-trace-decoder.git
FREEDOM_TRACE_DECODER_BRANCH := main
FREEDOM_TRACE_DECODER_MODULE := $(SRCDIR)/freedom-trace-decoder

ifneq ($(TARGET_GITURL),)
FREEDOM_TRACE_DECODER_GITURL := $(TARGET_GITURL)
endif
ifneq ($(TARGET_BRANCH),)
FREEDOM_TRACE_DECODER_BRANCH := $(TARGET_BRANCH)
endif

.PHONY: trace-decoder trace-decoder-package trace-decoder-regress trace-decoder-cleanup trace-decoder-flushup
trace-decoder: trace-decoder-package

$(FREEDOM_TRACE_DECODER_MODULE).$(FREEDOM_TRACE_DECODER_BRANCH):
	mkdir -p $(dir $@)
	rm -rf $(FREEDOM_TRACE_DECODER_MODULE)
	rm -rf $(FREEDOM_TRACE_DECODER_MODULE).*
	git clone $(FREEDOM_TRACE_DECODER_GITURL) $(FREEDOM_TRACE_DECODER_MODULE) --single-branch -b $(FREEDOM_TRACE_DECODER_BRANCH)
	cd $(FREEDOM_TRACE_DECODER_MODULE) && git submodule update --init --recursive
	date > $@

trace-decoder-package: \
		$(FREEDOM_TRACE_DECODER_MODULE).$(FREEDOM_TRACE_DECODER_BRANCH)
	$(MAKE) -C $(FREEDOM_TRACE_DECODER_MODULE) package BINDIR_PREFIX=$(abspath $(BINDIR_PREFIX))/ OBJDIR_PREFIX=$(abspath $(OBJDIR_PREFIX))/ EXTRA_OPTION=$(EXTRA_OPTION) EXTRA_SUFFIX=$(EXTRA_SUFFIX)

trace-decoder-regress: \
		$(FREEDOM_TRACE_DECODER_MODULE).$(FREEDOM_TRACE_DECODER_BRANCH)
	$(MAKE) -C $(FREEDOM_TRACE_DECODER_MODULE) regress BINDIR_PREFIX=$(abspath $(BINDIR_PREFIX))/ OBJDIR_PREFIX=$(abspath $(OBJDIR_PREFIX))/ EXTRA_OPTION=$(EXTRA_OPTION) EXTRA_SUFFIX=$(EXTRA_SUFFIX)

trace-decoder-cleanup:
	$(MAKE) -C $(FREEDOM_TRACE_DECODER_MODULE) cleanup BINDIR_PREFIX=$(abspath $(BINDIR_PREFIX))/ OBJDIR_PREFIX=$(abspath $(OBJDIR_PREFIX))/
	rm -rf $(FREEDOM_TRACE_DECODER_MODULE).*
	rm -rf $(FREEDOM_TRACE_DECODER_MODULE)

trace-decoder-flushup:
	$(MAKE) -C $(FREEDOM_TRACE_DECODER_MODULE) flushup BINDIR_PREFIX=$(abspath $(BINDIR_PREFIX))/ OBJDIR_PREFIX=$(abspath $(OBJDIR_PREFIX))/
