
FREEDOM_TRACE_DECODER_GITURL := https://github.com/sifive/freedom-trace-decoder.git
FREEDOM_TRACE_DECODER_COMMIT := 5ad26323fea1471268292af4c31bf89b7faacfa2

ifneq ($(CUSTOM_COMMIT),)
FREEDOM_TRACE_DECODER_COMMIT := $(CUSTOM_COMMIT)
endif

SRCNAME_FREEDOM_TRACE_DECODER := freedom-trace-decoder
SRCPATH_FREEDOM_TRACE_DECODER := $(SRCDIR)/$(SRCNAME_FREEDOM_TRACE_DECODER)

.PHONY: trace-decoder trace-decoder-package trace-decoder-regress trace-decoder-cleanup trace-decoder-flushup
trace-decoder: trace-decoder-package

$(SRCPATH_FREEDOM_TRACE_DECODER).$(FREEDOM_TRACE_DECODER_COMMIT):
	mkdir -p $(dir $@)
	rm -rf $(SRCPATH_FREEDOM_TRACE_DECODER)
	rm -rf $(SRCPATH_FREEDOM_TRACE_DECODER).*
	git clone $(FREEDOM_TRACE_DECODER_GITURL) $(SRCPATH_FREEDOM_TRACE_DECODER)
	cd $(SRCPATH_FREEDOM_TRACE_DECODER) && git checkout --detach $(FREEDOM_TRACE_DECODER_COMMIT)
	cd $(SRCPATH_FREEDOM_TRACE_DECODER) && git submodule update --init --recursive
	date > $@

trace-decoder-package: \
		$(SRCPATH_FREEDOM_TRACE_DECODER).$(FREEDOM_TRACE_DECODER_COMMIT)
	$(MAKE) -C $(SRCPATH_FREEDOM_TRACE_DECODER) package POSTFIXPATH=$(abspath .)/ EXTRA_OPTION=$(EXTRA_OPTION) EXTRA_SUFFIX=$(EXTRA_SUFFIX)

trace-decoder-regress: \
		$(SRCPATH_FREEDOM_TRACE_DECODER).$(FREEDOM_TRACE_DECODER_COMMIT)
	$(MAKE) -C $(SRCPATH_FREEDOM_TRACE_DECODER) regress POSTFIXPATH=$(abspath .)/ EXTRA_OPTION=$(EXTRA_OPTION) EXTRA_SUFFIX=$(EXTRA_SUFFIX)

trace-decoder-cleanup:
	$(MAKE) -C $(SRCPATH_FREEDOM_TRACE_DECODER) cleanup POSTFIXPATH=$(abspath .)/
	rm -rf $(SRCPATH_FREEDOM_TRACE_DECODER).*
	rm -rf $(SRCPATH_FREEDOM_TRACE_DECODER)

trace-decoder-flushup:
	$(MAKE) -C $(SRCPATH_FREEDOM_TRACE_DECODER) flushup POSTFIXPATH=$(abspath .)/
