
FREEDOM_TOOLCHAIN_METAL_GITURL := git@github.com:sifive/freedom-toolchain-metal.git
FREEDOM_TOOLCHAIN_METAL_BRANCH := main
FREEDOM_TOOLCHAIN_METAL_MODULE := $(SRCDIR)/freedom-toolchain-metal

ifneq ($(TARGET_GITURL),)
FREEDOM_TOOLCHAIN_METAL_GITURL := $(TARGET_GITURL)
endif
ifneq ($(TARGET_BRANCH),)
FREEDOM_TOOLCHAIN_METAL_BRANCH := $(TARGET_BRANCH)
endif

ifneq ($(TOOLSUITE_TOOLCHAIN_GITURL),)
FREEDOM_TOOLCHAIN_METAL_GITURL := $(TOOLSUITE_TOOLCHAIN_GITURL)
endif
ifneq ($(TOOLSUITE_TOOLCHAIN_BRANCH),)
FREEDOM_TOOLCHAIN_METAL_BRANCH := $(TOOLSUITE_TOOLCHAIN_BRANCH)
endif

.PHONY: toolchain-metal toolchain-metal-package toolchain-metal-regress toolchain-metal-cleanup toolchain-metal-flushup
toolchain-metal: toolchain-metal-package

.PHONY: toolchain toolchain-package toolchain-regress
toolchain-package: toolchain-metal-package
toolchain-regress: toolchain-metal-regress
toolchain: toolchain-metal

$(FREEDOM_TOOLCHAIN_METAL_MODULE).$(FREEDOM_TOOLCHAIN_METAL_BRANCH):
	mkdir -p $(dir $@)
	rm -rf $(FREEDOM_TOOLCHAIN_METAL_MODULE)
	rm -rf $(FREEDOM_TOOLCHAIN_METAL_MODULE).*
	git clone $(FREEDOM_TOOLCHAIN_METAL_GITURL) $(FREEDOM_TOOLCHAIN_METAL_MODULE) -b $(FREEDOM_TOOLCHAIN_METAL_BRANCH)
	cd $(FREEDOM_TOOLCHAIN_METAL_MODULE) && git submodule update --init --recursive
	date > $@

toolchain-metal-package: \
		$(FREEDOM_BINUTILS_METAL_MODULE).$(FREEDOM_BINUTILS_METAL_BRANCH) \
		$(FREEDOM_GCC_METAL_MODULE).$(FREEDOM_GCC_METAL_BRANCH) \
		$(FREEDOM_GDB_METAL_MODULE).$(FREEDOM_GDB_METAL_BRANCH) \
		$(FREEDOM_TOOLCHAIN_METAL_MODULE).$(FREEDOM_TOOLCHAIN_METAL_BRANCH)
	$(MAKE) -C $(FREEDOM_BINUTILS_METAL_MODULE) package BINDIR_PREFIX=$(abspath $(BINDIR_PREFIX))/ OBJDIR_PREFIX=$(abspath $(OBJDIR_PREFIX))/ EXTRA_OPTION=$(EXTRA_OPTION) EXTRA_SUFFIX=$(EXTRA_SUFFIX)
	$(MAKE) -C $(FREEDOM_GCC_METAL_MODULE) package BINDIR_PREFIX=$(abspath $(BINDIR_PREFIX))/ OBJDIR_PREFIX=$(abspath $(OBJDIR_PREFIX))/ EXTRA_OPTION=$(EXTRA_OPTION) EXTRA_SUFFIX=$(EXTRA_SUFFIX)
	$(MAKE) -C $(FREEDOM_GDB_METAL_MODULE) package BINDIR_PREFIX=$(abspath $(BINDIR_PREFIX))/ OBJDIR_PREFIX=$(abspath $(OBJDIR_PREFIX))/ EXTRA_OPTION=$(EXTRA_OPTION) EXTRA_SUFFIX=$(EXTRA_SUFFIX)
	$(MAKE) -C $(FREEDOM_TOOLCHAIN_METAL_MODULE) package BINDIR_PREFIX=$(abspath $(BINDIR_PREFIX))/ OBJDIR_PREFIX=$(abspath $(OBJDIR_PREFIX))/ EXTRA_OPTION=$(EXTRA_OPTION) EXTRA_SUFFIX=$(EXTRA_SUFFIX)

toolchain-metal-regress: \
		$(FREEDOM_TOOLCHAIN_METAL_MODULE).$(FREEDOM_TOOLCHAIN_METAL_BRANCH)
	$(MAKE) -C $(FREEDOM_TOOLCHAIN_METAL_MODULE) regress BINDIR_PREFIX=$(abspath $(BINDIR_PREFIX))/ OBJDIR_PREFIX=$(abspath $(OBJDIR_PREFIX))/ EXTRA_OPTION=$(EXTRA_OPTION) EXTRA_SUFFIX=$(EXTRA_SUFFIX)

toolchain-metal-cleanup:
	$(MAKE) -C $(FREEDOM_BINTUILS_METAL_MODULE) cleanup BINDIR_PREFIX=$(abspath $(BINDIR_PREFIX))/ OBJDIR_PREFIX=$(abspath $(OBJDIR_PREFIX))/
	rm -rf $(FREEDOM_BINTUILS_METAL_MODULE).*
	rm -rf $(FREEDOM_BINTUILS_METAL_MODULE)
	$(MAKE) -C $(FREEDOM_GCC_METAL_MODULE) cleanup BINDIR_PREFIX=$(abspath $(BINDIR_PREFIX))/ OBJDIR_PREFIX=$(abspath $(OBJDIR_PREFIX))/
	rm -rf $(FREEDOM_GCC_METAL_MODULE).*
	rm -rf $(FREEDOM_GCC_METAL_MODULE)
	$(MAKE) -C $(FREEDOM_GDB_METAL_MODULE) cleanup BINDIR_PREFIX=$(abspath $(BINDIR_PREFIX))/ OBJDIR_PREFIX=$(abspath $(OBJDIR_PREFIX))/
	rm -rf $(FREEDOM_GDB_METAL_MODULE).*
	rm -rf $(FREEDOM_GDB_METAL_MODULE)
	$(MAKE) -C $(FREEDOM_TOOLCHAIN_METAL_MODULE) cleanup BINDIR_PREFIX=$(abspath $(BINDIR_PREFIX))/ OBJDIR_PREFIX=$(abspath $(OBJDIR_PREFIX))/
	rm -rf $(FREEDOM_TOOLCHAIN_METAL_MODULE).*
	rm -rf $(FREEDOM_TOOLCHAIN_METAL_MODULE)

toolchain-metal-flushup:
	$(MAKE) -C $(FREEDOM_BINUTILS_METAL_MODULE) flushup BINDIR_PREFIX=$(abspath $(BINDIR_PREFIX))/ OBJDIR_PREFIX=$(abspath $(OBJDIR_PREFIX))/
	$(MAKE) -C $(FREEDOM_GCC_METAL_MODULE) flushup BINDIR_PREFIX=$(abspath $(BINDIR_PREFIX))/ OBJDIR_PREFIX=$(abspath $(OBJDIR_PREFIX))/
	$(MAKE) -C $(FREEDOM_GDB_METAL_MODULE) flushup BINDIR_PREFIX=$(abspath $(BINDIR_PREFIX))/ OBJDIR_PREFIX=$(abspath $(OBJDIR_PREFIX))/
	$(MAKE) -C $(FREEDOM_TOOLCHAIN_METAL_MODULE) flushup BINDIR_PREFIX=$(abspath $(BINDIR_PREFIX))/ OBJDIR_PREFIX=$(abspath $(OBJDIR_PREFIX))/
