
FREEDOM_DEVTOOL_MACHINE_GITURL := https://github.com/sifive/freedom-devtool-machine.git
FREEDOM_DEVTOOL_MACHINE_COMMIT := e079389277cd1e74c382ea85d2dfac52c210d3f7

ifneq ($(CUSTOM_COMMIT),)
FREEDOM_DEVTOOL_MACHINE_COMMIT := $(CUSTOM_COMMIT)
endif

SRCNAME_FREEDOM_DEVTOOL_MACHINE := freedom-devtool-machine
SRCPATH_FREEDOM_DEVTOOL_MACHINE := $(SRCDIR)/$(SRCNAME_FREEDOM_DEVTOOL_MACHINE)

.PHONY: devtool-machine devtool-machine-package devtool-machine-regress devtool-machine-cleanup devtool-machine-flushup
devtool-machine: devtool-machine-package

$(SRCPATH_FREEDOM_DEVTOOL_MACHINE).$(FREEDOM_DEVTOOL_MACHINE_COMMIT):
	mkdir -p $(dir $@)
	rm -rf $(SRCPATH_FREEDOM_DEVTOOL_MACHINE)
	rm -rf $(SRCPATH_FREEDOM_DEVTOOL_MACHINE).*
	git clone $(FREEDOM_DEVTOOL_MACHINE_GITURL) $(SRCPATH_FREEDOM_DEVTOOL_MACHINE)
	cd $(SRCPATH_FREEDOM_DEVTOOL_MACHINE) && git checkout --detach $(FREEDOM_DEVTOOL_MACHINE_COMMIT)
	cd $(SRCPATH_FREEDOM_DEVTOOL_MACHINE) && git submodule update --init --recursive
	date > $@

devtool-machine-package: \
		$(SRCPATH_FREEDOM_DEVTOOL_MACHINE).$(FREEDOM_DEVTOOL_MACHINE_COMMIT)
	$(MAKE) -C $(SRCPATH_FREEDOM_DEVTOOL_MACHINE) package POSTFIXPATH=$(abspath .)/ EXTRA_OPTION=$(EXTRA_OPTION) EXTRA_SUFFIX=$(EXTRA_SUFFIX)

devtool-machine-regress: \
		$(SRCPATH_FREEDOM_DEVTOOL_MACHINE).$(FREEDOM_DEVTOOL_MACHINE_COMMIT)
	$(MAKE) -C $(SRCPATH_FREEDOM_DEVTOOL_MACHINE) regress POSTFIXPATH=$(abspath .)/ EXTRA_OPTION=$(EXTRA_OPTION) EXTRA_SUFFIX=$(EXTRA_SUFFIX)

devtool-machine-cleanup:
	$(MAKE) -C $(SRCPATH_FREEDOM_DEVTOOL_MACHINE) cleanup POSTFIXPATH=$(abspath .)/
	rm -rf $(SRCPATH_FREEDOM_DEVTOOL_MACHINE).*
	rm -rf $(SRCPATH_FREEDOM_DEVTOOL_MACHINE)

devtool-machine-flushup:
	$(MAKE) -C $(SRCPATH_FREEDOM_DEVTOOL_MACHINE) flushup POSTFIXPATH=$(abspath .)/
