
FREEDOM_XC3SPROG_GITURL := git@github.com:sifive/freedom-xc3sprog.git
FREEDOM_XC3SPROG_BRANCH := main
FREEDOM_XC3SPROG_MODULE := $(SRCDIR)/freedom-xc3sprog

ifneq ($(TARGET_GITURL),)
FREEDOM_XC3SPROG_GITURL := $(TARGET_GITURL)
endif
ifneq ($(TARGET_BRANCH),)
FREEDOM_XC3SPROG_BRANCH := $(TARGET_BRANCH)
endif

.PHONY: xc3sprog xc3sprog-package xc3sprog-regress xc3sprog-cleanup xc3sprog-flushup
xc3sprog: xc3sprog-package

$(FREEDOM_XC3SPROG_MODULE).$(FREEDOM_XC3SPROG_BRANCH):
	mkdir -p $(dir $@)
	rm -rf $(FREEDOM_XC3SPROG_MODULE)
	rm -rf $(FREEDOM_XC3SPROG_MODULE).*
	git clone $(FREEDOM_XC3SPROG_GITURL) $(FREEDOM_XC3SPROG_MODULE) --single-branch -b $(FREEDOM_XC3SPROG_BRANCH)
	cd $(FREEDOM_XC3SPROG_MODULE) && git submodule update --init --recursive
	date > $@

xc3sprog-package: \
		$(FREEDOM_XC3SPROG_MODULE).$(FREEDOM_XC3SPROG_BRANCH)
	$(MAKE) -C $(FREEDOM_XC3SPROG_MODULE) package BINDIR_PREFIX=$(abspath $(BINDIR_PREFIX))/ OBJDIR_PREFIX=$(abspath $(OBJDIR_PREFIX))/ EXTRA_OPTION=$(EXTRA_OPTION) EXTRA_SUFFIX=$(EXTRA_SUFFIX)

xc3sprog-regress: \
		$(FREEDOM_XC3SPROG_MODULE).$(FREEDOM_XC3SPROG_BRANCH)
	$(MAKE) -C $(FREEDOM_XC3SPROG_MODULE) regress BINDIR_PREFIX=$(abspath $(BINDIR_PREFIX))/ OBJDIR_PREFIX=$(abspath $(OBJDIR_PREFIX))/ EXTRA_OPTION=$(EXTRA_OPTION) EXTRA_SUFFIX=$(EXTRA_SUFFIX)

xc3sprog-cleanup:
	$(MAKE) -C $(FREEDOM_XC3SPROG_MODULE) cleanup BINDIR_PREFIX=$(abspath $(BINDIR_PREFIX))/ OBJDIR_PREFIX=$(abspath $(OBJDIR_PREFIX))/
	rm -rf $(FREEDOM_XC3SPROG_MODULE).*
	rm -rf $(FREEDOM_XC3SPROG_MODULE)

xc3sprog-flushup:
	$(MAKE) -C $(FREEDOM_XC3SPROG_MODULE) flushup BINDIR_PREFIX=$(abspath $(BINDIR_PREFIX))/ OBJDIR_PREFIX=$(abspath $(OBJDIR_PREFIX))/
