
FREEDOM_SDK_UTILITIES_GITURL := git@github.com:sifive/freedom-sdk-utilities.git
FREEDOM_SDK_UTILITIES_BRANCH := main
FREEDOM_SDK_UTILITIES_MODULE := $(SRCDIR)/freedom-sdk-utilities

ifneq ($(TARGET_GITURL),)
FREEDOM_SDK_UTILITIES_GITURL := $(TARGET_GITURL)
endif
ifneq ($(TARGET_BRANCH),)
FREEDOM_SDK_UTILITIES_BRANCH := $(TARGET_BRANCH)
endif

.PHONY: sdk-utilities sdk-utilities-package sdk-utilities-regress sdk-utilities-cleanup sdk-utilities-flushup
sdk-utilities: sdk-utilities-package

$(FREEDOM_SDK_UTILITIES_MODULE).$(FREEDOM_SDK_UTILITIES_BRANCH):
	mkdir -p $(dir $@)
	rm -rf $(FREEDOM_SDK_UTILITIES_MODULE)
	rm -rf $(FREEDOM_SDK_UTILITIES_MODULE).*
	git clone $(FREEDOM_SDK_UTILITIES_GITURL) $(FREEDOM_SDK_UTILITIES_MODULE) --single-branch -b $(FREEDOM_SDK_UTILITIES_BRANCH)
	cd $(FREEDOM_SDK_UTILITIES_MODULE) && git submodule update --init --recursive
	date > $@

sdk-utilities-package: \
		$(FREEDOM_SDK_UTILITIES_MODULE).$(FREEDOM_SDK_UTILITIES_BRANCH)
	$(MAKE) -C $(FREEDOM_SDK_UTILITIES_MODULE) package BINDIR_PREFIX=$(abspath $(BINDIR_PREFIX))/ OBJDIR_PREFIX=$(abspath $(OBJDIR_PREFIX))/ EXTRA_OPTION=$(EXTRA_OPTION) EXTRA_SUFFIX=$(EXTRA_SUFFIX)

sdk-utilities-regress: \
		$(FREEDOM_SDK_UTILITIES_MODULE).$(FREEDOM_SDK_UTILITIES_BRANCH)
	$(MAKE) -C $(FREEDOM_SDK_UTILITIES_MODULE) regress BINDIR_PREFIX=$(abspath $(BINDIR_PREFIX))/ OBJDIR_PREFIX=$(abspath $(OBJDIR_PREFIX))/ EXTRA_OPTION=$(EXTRA_OPTION) EXTRA_SUFFIX=$(EXTRA_SUFFIX)

sdk-utilities-cleanup:
	$(MAKE) -C $(FREEDOM_SDK_UTILITIES_MODULE) cleanup BINDIR_PREFIX=$(abspath $(BINDIR_PREFIX))/ OBJDIR_PREFIX=$(abspath $(OBJDIR_PREFIX))/
	rm -rf $(FREEDOM_SDK_UTILITIES_MODULE).*
	rm -rf $(FREEDOM_SDK_UTILITIES_MODULE)

sdk-utilities-flushup:
	$(MAKE) -C $(FREEDOM_SDK_UTILITIES_MODULE) flushup BINDIR_PREFIX=$(abspath $(BINDIR_PREFIX))/ OBJDIR_PREFIX=$(abspath $(OBJDIR_PREFIX))/
