
FREEDOM_TOOLCHAIN_METAL_GITURL := https://github.com/sifive/freedom-toolchain-metal.git
FREEDOM_TOOLCHAIN_METAL_COMMIT := main

ifneq ($(CUSTOM_COMMIT),)
FREEDOM_TOOLCHAIN_METAL_COMMIT := $(CUSTOM_COMMIT)
endif

SRCNAME_FREEDOM_TOOLCHAIN_METAL := freedom-toolchain-metal
SRCPATH_FREEDOM_TOOLCHAIN_METAL := $(SRCDIR)/$(SRCNAME_FREEDOM_TOOLCHAIN_METAL)

.PHONY: toolchain-metal toolchain-metal-package toolchain-metal-regress toolchain-metal-cleanup toolchain-metal-flushup
toolchain-metal: toolchain-metal-package

.PHONY: toolchain toolchain-package toolchain-regress
toolchain-package: toolchain-metal-package
toolchain-regress: toolchain-metal-regress
toolchain: toolchain-metal

$(SRCPATH_FREEDOM_TOOLCHAIN_METAL).$(FREEDOM_TOOLCHAIN_METAL_COMMIT):
	mkdir -p $(dir $@)
	rm -rf $(SRCPATH_FREEDOM_TOOLCHAIN_METAL)
	rm -rf $(SRCPATH_FREEDOM_TOOLCHAIN_METAL).*
	git clone $(FREEDOM_TOOLCHAIN_METAL_GITURL) $(SRCPATH_FREEDOM_TOOLCHAIN_METAL) -b $(FREEDOM_TOOLCHAIN_METAL_COMMIT)
	cd $(SRCPATH_FREEDOM_TOOLCHAIN_METAL) && git submodule update --init --recursive
	date > $@

toolchain-metal-package: \
		$(SRCPATH_FREEDOM_BINUTILS_METAL).$(FREEDOM_BINUTILS_METAL_COMMIT) \
		$(SRCPATH_FREEDOM_GCC_METAL).$(FREEDOM_GCC_METAL_COMMIT) \
		$(SRCPATH_FREEDOM_GDB_METAL).$(FREEDOM_GDB_METAL_COMMIT) \
		$(SRCPATH_FREEDOM_TOOLCHAIN_METAL).$(FREEDOM_TOOLCHAIN_METAL_COMMIT)
	$(MAKE) -C $(SRCPATH_FREEDOM_BINUTILS_METAL) package POSTFIXPATH=$(abspath $(POSTFIXPATH))/ EXTRA_OPTION=$(EXTRA_OPTION) EXTRA_SUFFIX=$(EXTRA_SUFFIX)
	$(MAKE) -C $(SRCPATH_FREEDOM_GCC_METAL) package POSTFIXPATH=$(abspath $(POSTFIXPATH))/ EXTRA_OPTION=$(EXTRA_OPTION) EXTRA_SUFFIX=$(EXTRA_SUFFIX)
	$(MAKE) -C $(SRCPATH_FREEDOM_GDB_METAL) package POSTFIXPATH=$(abspath $(POSTFIXPATH))/ EXTRA_OPTION=$(EXTRA_OPTION) EXTRA_SUFFIX=$(EXTRA_SUFFIX)
	$(MAKE) -C $(SRCPATH_FREEDOM_TOOLCHAIN_METAL) package POSTFIXPATH=$(abspath $(POSTFIXPATH))/ EXTRA_OPTION=$(EXTRA_OPTION) EXTRA_SUFFIX=$(EXTRA_SUFFIX)

toolchain-metal-regress: \
		$(SRCPATH_FREEDOM_TOOLCHAIN_METAL).$(FREEDOM_TOOLCHAIN_METAL_COMMIT)
	$(MAKE) -C $(SRCPATH_FREEDOM_TOOLCHAIN_METAL) regress POSTFIXPATH=$(abspath $(POSTFIXPATH))/ EXTRA_OPTION=$(EXTRA_OPTION) EXTRA_SUFFIX=$(EXTRA_SUFFIX)

toolchain-metal-cleanup:
	$(MAKE) -C $(SRCPATH_FREEDOM_BINTUILS_METAL) cleanup POSTFIXPATH=$(abspath $(POSTFIXPATH))/
	rm -rf $(SRCPATH_FREEDOM_BINTUILS_METAL).*
	rm -rf $(SRCPATH_FREEDOM_BINTUILS_METAL)
	$(MAKE) -C $(SRCPATH_FREEDOM_GCC_METAL) cleanup POSTFIXPATH=$(abspath $(POSTFIXPATH))/
	rm -rf $(SRCPATH_FREEDOM_GCC_METAL).*
	rm -rf $(SRCPATH_FREEDOM_GCC_METAL)
	$(MAKE) -C $(SRCPATH_FREEDOM_GDB_METAL) cleanup POSTFIXPATH=$(abspath $(POSTFIXPATH))/
	rm -rf $(SRCPATH_FREEDOM_GDB_METAL).*
	rm -rf $(SRCPATH_FREEDOM_GDB_METAL)
	$(MAKE) -C $(SRCPATH_FREEDOM_TOOLCHAIN_METAL) cleanup POSTFIXPATH=$(abspath $(POSTFIXPATH))/
	rm -rf $(SRCPATH_FREEDOM_TOOLCHAIN_METAL).*
	rm -rf $(SRCPATH_FREEDOM_TOOLCHAIN_METAL)

toolchain-metal-flushup:
	$(MAKE) -C $(SRCPATH_FREEDOM_BINUTILS_METAL) flushup POSTFIXPATH=$(abspath $(POSTFIXPATH))/
	$(MAKE) -C $(SRCPATH_FREEDOM_GCC_METAL) flushup POSTFIXPATH=$(abspath $(POSTFIXPATH))/
	$(MAKE) -C $(SRCPATH_FREEDOM_GDB_METAL) flushup POSTFIXPATH=$(abspath $(POSTFIXPATH))/
	$(MAKE) -C $(SRCPATH_FREEDOM_TOOLCHAIN_METAL) flushup POSTFIXPATH=$(abspath $(POSTFIXPATH))/
